### PR TITLE
Update to work with Py2 and Py3

### PR DESCRIPTION
**Pull request by TayHobbs**

### CODE REVIEW

**Comment by mattjmorrison-imt** [comment]
Does this need to wait for imaging to deploy before it can be merged?

**Comment by TayHobbs** [comment]
Yes, I believe imaging is the last thing to go

**Comment by mattjmorrison-imt** [comment]
We will probably also need to wait for the new auth to deploy because of this: http://ci.imtapps.com/view/Status/job/Auth_Prod_Deploy/

**Comment by Mr-TaylorHobbs** [comment]
@mattjmorrison-imt Is this PR good to go now?

**Comment by mattjmorrison-imt** [comment]
I believe it is...

**Pull request merged**
